program: main.py
method: grid
name: chess-sl-dev-sweep
metric:
  name: avg_moves
  goal: maximize
parameters:
  num_epochs:
    values: [10]
  n_blocks:
    values: [0, 1]
  n_channels:
    values: [8, 16]
  batch_size:
    values: [128]
  learning_rate_multiplier:
    values: [1]
  optimizer:
    values: ['ADAM']
  n_hidden:
    values: [1024]
  num_training_examples:
    values: [10000]